In [27]:
import numpy as np
arr = np.arange(5,16)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [3]:
arr = np.linspace(2,8,15)
print(arr)

[2.         2.42857143 2.85714286 3.28571429 3.71428571 4.14285714
 4.57142857 5.         5.42857143 5.85714286 6.28571429 6.71428571
 7.14285714 7.57142857 8.        ]


In [5]:
arr = np.random.randint(0, 11, size=(3, 3))
print(arr)


[[3 7 6]
 [3 7 8]
 [0 7 0]]


In [7]:
matflt = np.random.random(size=(2,2))
print(matflt)

[[0.06574053 0.3256937 ]
 [0.35707301 0.67878683]]


In [9]:
arr = np.random.randint(5, 12, size=(3, 3))
newarr = arr[::-1]
print(arr)
print(newarr)

[[ 8  7  5]
 [ 9  7 10]
 [ 7 11 11]]
[[ 7 11 11]
 [ 9  7 10]
 [ 8  7  5]]


In [16]:
import numpy as np
arr = np.arange(12)
mat = arr.reshape(3,4)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
mat = np.arange(1,10)
matrix = mat.reshape(3,3)
Transpose = np.transpose(matrix)
print(matrix)
print(Transpose)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
arr = np.arange(1,7)
arr1 = [2, 4, 6, 8, 10, 12]
mul = arr * arr1
print(mul)

[ 2  8 18 32 50 72]


In [22]:
arr = np.random.randint(1, 100, size=(3, 3,3))
print(arr)

[[[20 86 14]
  [ 5 49 81]
  [58 44 55]]

 [[67 99 29]
  [89 48 85]
  [27 87  9]]

 [[74  5 30]
  [28 14 99]
  [99 85 83]]]


In [26]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

arr3d = arr.reshape(2,2,4)
print(arr3d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
