In [1]:
import numpy as np
matrix = np.eye(4)

print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
arr = np.arange(1,11)*2
print(arr)


[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
arr = np.array([9, 16, 25, 36])
sqrt = np.sqrt(arr)
print(sqrt)

[3. 4. 5. 6.]


In [10]:
ones = np.ones((4, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr = np.array([1, 7, 3, 9, 5])
arr[arr%2 != 0]**=2
print(arr)


[ 1 49  9 81 25]


In [23]:
array = np.random.random(size = (4,4))
mean = np.mean(array)
print(mean)
print(array)


0.42984815259715586
[[0.64024882 0.42740989 0.80107241 0.04325401]
 [0.00937506 0.46544877 0.56879915 0.29029022]
 [0.19863001 0.907323   0.0807588  0.05805071]
 [0.70920666 0.35412321 0.92835289 0.39522682]]


In [28]:
arr = np.arange(0,10)
arr[arr%2!=0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [4]:
import numpy as np

arr = np.random.randint(0, 10, size=(5, 5))

innerelements = arr[1:-1, 1:-1]

print(arr)
print(innerelements)
   

[[1 0 4 7 7]
 [5 4 0 0 9]
 [2 7 1 7 1]
 [9 6 5 4 5]
 [2 6 1 5 6]]
[[4 0 0]
 [7 1 7]
 [6 5 4]]


In [6]:
import numpy as np

matrix = np.random.randint(1, 101, size=(4, 4))

average = np.mean(matrix)

result = np.where(matrix > average , 1, 0)

print(matrix)

print(result)


[[ 2 14 48 65]
 [81 16 67 41]
 [88 16 50 65]
 [17 63 24  3]]
[[0 0 1 1]
 [1 0 1 0]
 [1 0 1 1]
 [0 1 0 0]]


In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)

print(result)


[[19 22]
 [43 50]]


In [8]:
import numpy as np

arr = np.random.randint(0, 10, size=(4, 3, 2))

sum = np.sum(arr, axis=2)

print(arr)

print(sum)


[[[2 8]
  [1 4]
  [4 7]]

 [[0 5]
  [6 0]
  [1 2]]

 [[7 8]
  [2 6]
  [8 0]]

 [[0 1]
  [9 8]
  [1 5]]]
[[10  5 11]
 [ 5  6  3]
 [15  8  8]
 [ 1 17  6]]


In [9]:
import numpy as np

arr = np.random.randint(0, 100, size=(2, 4, 3))

mean = np.mean(arr, axis=1)

print(arr)

print(mean)


[[[75 59 51]
  [48 19 81]
  [59 46 26]
  [56 85 55]]

 [[39 96  2]
  [70 22 33]
  [20 49 81]
  [38 22 19]]]
[[59.5  52.25 53.25]
 [41.75 47.25 33.75]]
