In [1]:
import numpy as np 
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[9,8,7],[10,11,12]]])
print(type(arr))
print(arr.ndim)

<class 'numpy.ndarray'>
3


In [15]:
arr = np.array([[[1,2,3],[4,5,6]],[[9,8,7],[10,11,12]]])
print(arr[1,0:2,2])

[ 7 12]


In [8]:
arr = np.array([1,2,3,4,5], ndmin=3)
print(arr)
print(arr.ndim)

[[[1 2 3 4 5]]]
3


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

In [24]:
import numpy as np

arr = np.array([1, 2, 3], dtype='i')

print(arr)
print(arr.dtype)

TypeError: data type 'i32' not understood