In [1]:
import numpy as np

array = np.arange(2, 11).reshape(3, 3)
print(array)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
import numpy as np

array = np.array([[2, 3, 4],
                  [5, 6, 7],
                  [8, 9, 10]])

array[1] = 1
print(array)


[[ 2  3  4]
 [ 1  1  1]
 [ 8  9 10]]


In [3]:
import numpy as np

matrix = np.eye(4)

Triangle = np.triu(matrix)

print(matrix)

print(Triangle)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
import numpy as np

array = np.random.randint(1, 101, size=20)

mean = np.mean(array)
deviation = np.std(array)

print(array)
print(mean)
print(deviation)


[ 46  12  35  87   3  45   8  28   2  78  74  63  57  74  41 100  27  49
  71  83]
49.15
28.82754758906834


In [1]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6]])

B = np.array([[7, 8],[9, 10],[11, 12]])

C = np.dot(A, B)

print(A)

print(B)

print(C)


[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [3]:
import numpy as np

arr = np.arange(12)

arr3d = arr.reshape(2, 2, 3)

print(arr)

print(arr3d)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [4]:
import numpy as np

two_d_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

one_d_array = np.array([10, 20, 30])

result_array = two_d_array + one_d_array[:, np.newaxis]

print(result_array)


[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [5]:
import numpy as np

arr = np.array([1, 2, np.nan, 4])

mean_value = np.nanmean(arr)

arr[np.isnan(arr)] = mean_value

print(arr)


[1.         2.         2.33333333 4.        ]


In [6]:
import numpy as np

array = np.random.rand(10)

array.sort()

print(array)


[0.03755666 0.08332503 0.19705349 0.21624817 0.25769332 0.50465106
 0.51430704 0.76380033 0.92709628 0.99708025]


In [7]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1  # odd rows, even columns
checkerboard[::2, 1::2] = 1  # even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
